WITH artist_list AS (
  SELECT LOWER(TRIM(artist_name)) AS artist_name
  FROM UNNEST([
    'mitro','xavier garcia','rocio pluas','mies','miles regis','javier torices','niki hare',
    'caroline hufnagel','ian edwards','nikolaos nikolaidis','chuck hipsher','bruce rubenstein',
    'jessica m. chaix','olivier messas','weatherly stroh','john martono','sherie harkins',
    'eugen dick','wojtek babski','suzanne howe','fong fai','nelina trubach-moshnikova',
    'danielle vasa','rasa kluonius','irina biatturi','jean soyer','eddy vitalone',
    'cristina figarola','gordon hopkins','peter w. hart','davide d\'alba','christian develter',
    'ossola raffaello','pablo sinai','mr brainwash','annemiki bok','francisco vazquez',
    'albert madaula','behnaz larsen','gerard maitre','teppei ikehila','alfredo sanchez',
    'alfonso sanchez','paolo braccini','jean louis mendrisse','nikolaos schizas',
    'antonio di viccaro','martina hamrik','le anh tuan le anh','todd koelmel','andre durand',
    'yann crenn','viktoria adkozalova','thomas gromas','olivier lavorel','christoph maderthaner',
    'jason forcier','christine falk','ernestine tahedl','costel iarca','claudia barbu',
    'natalia rozmus - esparza','yongho park','isabelle derecque','giovanni sanesi',
    'sergej sologub','michel cren pietsch','ta byrne','rob van hoek','keith thomson',
    'tatiana yabloed','marie rouach','david sheldon','pablo contrisciani','denny baggen',
    'aleksandr ilichev','jurgen angeler','katja fischer','alain mandon','anna sidi-yacoub',
    'christine pacaud','julian adrat','hiroshi wada','joseph adolphe','peter vahlefeld',
    'jordi artigas','otilia mandescu canavra','nadee','odile pinto-corbin','everett duarte',
    'paco munoz santana','kelsey irvin','bjørnar aaslund','jorge nava','shawn kolodny',
    'nathan chantob','stefanie von quast','michael goro','michel calvet','lezzueck coosemans',
    'hassan massoudy','aziseh emmanuel','gilles candelier','peter nottrott','karoline kroiß',
    'eka peradze','marie-astrid grivet','cyrille borgnet','stephane villafane','yutao ge',
    'palut marod','han','riccardo vitiello','joong-hyun park','karlien hamel-kuperus',
    'elisa boughner','alisa onipchenko-cherniakovska','angelika kienberger',
    'holger muhlbauer-gardemin','roberto talignani','angie brooksby-arcangioli',
    'nadezda stupina','alessandro siviglia','stanislav sidorov','sanuj birla','sylvia goebel',
    'andrea kohn','irene hoff','paula berteotti','vera & sergey goncharenko','benoit guerin',
    'gerard neyb','lourdes ral','dmitry spiros','sophie petetin','ivan pili','michel cornu',
    'stas agapitov','alain rolland','gregoire devin','chantal delos','steffi goddard',
    'tomasa martin','glib franko','philippe abril','matous hasa','juan del balso',
    'kiseok kim','xavier wttrwulghe','luca brandi','paul picka','diana malivani',
    'thierry van quickenborne','ole hedeager','amanda wigglesworth','susanne wind',
    'inez froehlich','toby wright','raul arenas','lamiel','sylwia synak','graham gercken',
    'kari feuer','hugo aguilar','olivia de posson','dominika block','amede flum',
    'christine barres','arno bruse','penelope clot grau','eva volf','igor medvedev',
    'norma alonzo','luc villard','lucca r colombelli','veronica vilsan','kamila ossowska',
    'mazel jalix','nathanael koffi','emanuele vittorioso','jordi machi','ali mourabet',
    'benoit havard','janos lukacs','yari ostovany','angel celada','giusy lauriola',
    'brigitte dravet','sniege','malik','svetlana melik-nubarova','francesca dalla benetta',
    'sergey khachatryan','andres rueda','jerome royer','nana artamonova','carole bressan',
    'jack mason','richard martin','dmitry oleyn','fatin rahmouni','riccardo perrone',
    'yana medow','tina paulus','irina laube','julia ismambetova','helle rask crawford',
    'kalina brajkovska','alexandr sergeev','julia a. etedi','genevieve jost','micky goldstein',
    'sosta sonksen','roberta diazzi','per nylen','zelie belcour','massimo villa',
    'parscha mirghawameddin','laurent roch','dina d\'argo','jennifer diekmann',
    'roswitha schumacher-kuckelkorn','fred boutet','silvana hope','marina krasnitskaya',
    'aj burns','angel mieres','evgeni gordiets','christian pieroni','ibrahim jalal',
    'alex bras','sof - sophie voigt-chadeyron','friedrich wurm','marina koutsospyrou',
    'tatiana harizanova','mathilde polidori','romain veillon','sook kim','armin volckers',
    'eduard belsky','josep costa vila','chanida aroonrungsi','toctoc','javiera estrada',
    'barbara nati','lisa elley','francois faucher','alice cescatti','petra meikle de vlas',
    'pol ledent','sylvie hamou','victor tkachenko','petra heck','ruth bucher',
    'cecile duchene-malissin','sylvie gerard','alexandra kapogianni-beth','damola ayegbayo',
    'emilie chene','fredi gertsch','inelouise mourick','perceval graells','gaspard mitz',
    'geca','kris gebhardt','thomas ritter','valerie depadova','pascal heranval',
    'merita seitz','dominic virtosu','ekaterina ermilkina','titti garelli','karen axikyan',
    'frederic baccalino','sergei chernyakovsky','frob','sebastian merk','wo$h wo$h',
    'joseph cela','conny niehoff','jia yuan hua','petra kasten','artem brazhnik',
    'jan van der ster','andrea serra','mauro bergonzoli','cecco mariniello','valeria pesce',
    'konstantin kansky','donatella marraoni','jose soler art','hilma koelman','agusil',
    'nansky','maude ovize','kamil vojnar','valentina andrees-reschetizka','jimmy law',
    'gianluca cremonesi','bruno cantais','debbie lee','warren keating','koen lybaert',
    'sabina d\'antonio','effat pourhasani','karen und simone lehmann','lionel chevalier',
    'dieter langer','min mun','anne boddeker','iryna kastsova','alessandra b-b','chorgy',
    'patrick marie','ali shamsi','denis de mot','sabrina seck','carles azcon',
    'catherine senechal','perrotte','eusebio lopez','catherine redmayne','weronika braun',
    'chris veeneman','alison bignon','georges troubat','danny frede','vincent bardou',
    'maryline lemaitre','ve boisvert','maria kammerer','kerstin sokoll','sofia fresia',
    'andrey visokinsky','fulvio dot','wawapod','adriana bernet','axelle bosler',
    'ilona hendriks','andrew weir','benny arte','monika riethmueller','lara broecke',
    'vincent baldassano','katharina gerold','vera kochubey','julia borg','femke kock',
    'jesus manuel moreno','daniel giacchi','milla laborde','christine barth mroz',
    'cristina barrera','rie kono','jeanne saint cheron','diegokoi','carolina bellachi',
    'mark tennant','joelle kem lika','sally k. smith','angeles m. pomata','olivier desvaux',
    'hanne karch','andrea solaja','esther glina montagner','liliya nikolova',
    'egle karlonaite','jose blanco lorenzo blanco lorenzo','luc mora','francois benett',
    'alejandra patricia','maria moretti','trong thuong tran','stephane braud',
    'oliver weiller','petra schott','nathalie ollagnier','alexander klemens','andrea ehret',
    'jesus nieto pantoja','antonino puliafico','felipe alarcon','jurgen bubeck',
    'thomas leung','angie wright','dmitry yakhouski','anke blaue','gor avetisyan',
    'antonio varas de la rosa','nicolae prisac','yannick bouillault','marie-madeleine vitrolles',
    'dietmar brixy','carolin beyer','yasmin aly','michael rofka','dinah wakefield',
    'frantisek kuco','chantal longeon','lelya borisenko','jean-michel yon','seb',
    'amelie vogel','lana frey','joao figueiredo','jean paul courchia','nataliya bagatskaya',
    'alessio luzzi','hieronymus proske','wilfrid moizan','yvonne coomber','andreea zecheru',
    'behshad arjomandi','stephan mundi','phung van tue','manuel leonardi','beata kozak',
    'kastro','olivier boissinot','valeria radzievska','jeannine platz','karin vermeer',
    'mindy rodman paul white','ru8icon','siegbert hahn','valerie vescovi','marco ronga',
    'santhosh c h','pavel guliaev','dagmar vogt','filiberto montesinos castanon',
    'petra rader','sabine huening','anna cher','chantal parise','anja spagl','arvid boecker',
    'jean-pierre kunkel','jfk','belinda nadwie','carlos martin','marc gonz','monique lipsch',
    'ciro palumbo','natalia schafer','felicitas willgeroth','viktors svikis','michael lam',
    'hugo pondz','annet loginova','cyril pienon','astrid esslinger','william kendall',
    'laurent dorchin','joelle troussier','ute bivona','yaroslav yasenev','annco miura',
    'flavia birsan','barbara kroll','olya jonas','oxana zaika','lotte teussink',
    'marie manon corbeil','dake wong','jamal bassiouni','jean-marie gitard',
    'liuba & javier torres','laurentiu dimisca','richard montpetit','andrea marchesini',
    'maria burgaz','volker schrank','manfred paar','anushka kempken','hrvoje majer',
    'vytautas laisonas','francois benoit-lison','antonella benanzato','marc schmitz',
    '千佳子 伊藤','rossen stanoev','roberto gutierrez curras','adrienne egger',
    'jutta rika bressem','birgitta seghers','eva hidalgo','peter locascio','furio torracchi',
    'vasyl kolodiy','sophie raskopf','anders post','ralau','eva dahn rubin','carl chapple',
    'jan hendriks','alessandra carloni','barbara schauß','diana krinninger','marie amedro',
    'jose cacho','joan llaverias','dita luse','jan teunissen','yermine richardson',
    'kailin zhao','rogerm','carole fournier','delphine blais','gabriela lavezzari',
    'mona berga','jorg kuplens','guyla artiste','sylvia paul','viktoria lapteva',
    'andrew osta','rudyard heaton','marko brajkovic','pilar lopez baez','fares micue',
    'kerstin wagner','kasia rayska','ana sanchez lucas','maurizio cavicchiola',
    'cristoforo russo','fiona maclean','jean-pierre andre leclercq','patricia paolozzi cain',
    'harry holland','victoria horkan','nelly van nieuwenhuijzen','angel moyano rivas',
    'anastassia skopp','bianca prettau','yossi kotler','bartolomeo gatto','liubov kuptsova',
    'mykola kuryliuk','pablo luzardo','david onen','andrei sitsko','ulyana korol',
    'david truman','mary gallagher stout','gerardo gerardi','chantal bucco','gerard capron',
    'nina boos','jovan srijemac','bebar','zoe mactaggart','andrey smirnoff','herman reichold',
    'vanya georgieva','peter matzat','leon lollipop','gian-franco riboni','sandra yagi',
    'aurore millet','gordon bruce','annette freymuth','jos kivits','lars tunebo',
    'marcell dergecz','ezio ranaldi','alfred freddy krupa','jonah ward','renate linnemeier',
    'brigitte rochas','david vall','jaro palmu','ovidiu kloska','sandy welch','marion cadet',
    'francois millon','aliz polgar','pelayo ortega','macarena sanz','alex hook krioutchkov',
    'ibrahima soumare','amedeo cianci','pinar akbaba','yo franklin','nikolai gritsanchuk',
    'corinne boucher','kelly allison','alejos','agnieszka kozien','emmanuelle pellet',
    'flore betty','amandyne steropes','kaitlin johnson','alice roy','francesco polazzi',
    'laura tietjens','dan mason','patrick pearson','petra penz','nathalie gribinski',
    'karel stoop','stathis alexopoulos','sanne rasmussen','laurent allory','stavri kalinov',
    'patrick marin','art taghera','olga novokhatska','marcos zrihen','alessandro masera',
    'eleni pratsi','jody','davide zappia','claudia molle','emily starck','rebecca pierce',
    'jan cilliers de wet','joerg bollin','franziska ostermeier','dima filatov','james cummins',
    'le hai linh','jeannette perreault','wolf e. schultz','thomas pourcelot wonsungee',
    'sophie duplain','bruno varatojo','zoe chigi (valentina toma\')','max rovira',
    'nathalie roure','slawek gora','tomas hammar','andrea alonso','bruno richard',
    'horst kordes','paolo perfranceschi','cesare papiccio','noah hummer','aykaz arzumanyan',
    'viktoria ganhao','ekaterina chigodaeva','britta clausnitzer','nils peters','pavel sipkin',
    'tartaros','natalia kuruch','barbara piatti','frany-la-chipie','lukas kandl',
    'harald wolff','luis medina manso','susanne zemrosser','michael freudenberg',
    'tatiana hellum','david daoud','julia abele','barbara padron hernandez','tp hardisty',
    'melane','vanessa onuk','roger haus','aleksandra osa','makiwa mutomba','elena hromova',
    'natalya gripas','line .c','goyo dominguez','lina redford','francois-regis lemonnier',
    'jose higuera','caroline brisset','soo beng lim','kirsty may hall','philip hearsey',
    'darren thompson','luigi iona','stefan dimovski','irene sheri','didier avril',
    'alina hubarenko','marie-laure souq','elena dmitrenko','muriel cayet',
    'krisztina dozsa-farkas','pascal dabere','kate graham','bill santelli','jonathan mcafee',
    'ksenia yarovaya','simone monney','andrii kovalyk','mark engel','white shirt art',
    'kristin kossi','tom blood','serguei borodouline','hasso heybrock','joan march torrandell',
    'gabriela de la serna','leni winkelmann','nikolaus weiler','claire desjardins',
    'isabel mahe','jacqueline aleksandrova','ilya volykhine','adrian arnau','john m white',
    'anastasiia grygorieva','nadine hardy','bernd vogel','florian japp','corine ko',
    'nataliya rozhdestvenskaya','stjepko mamic','rakhmet redzhepov','marco stazzini aka stoz',
    'ozlem thompson','ewa czarniecka','jacky ananou','pierre ziegler','mauro di berardino',
    'kspersee','edith torony','chalda maloff','elaine marx','gianni mattu','alexandra machmar',
    'henrik schrat','daheaven art','bernd erich gall','pascal geyre','isabel tapias',
    'alex morlotez','guillem crespi alemany','ricardo llinares','ruslan khais',
    'arsentij pawlow','misako street art','robert hettich','marita tobner','daniel murgatroyd',
    'kaza','eric sher','geraldine morales','megi balzer','marjon trap','sinao',
    'vincent verdeguer','isa paul','gregg chadwick','xiaoyang galas','clivia bauer',
    'erik bonnet','sebastian luksch','mariola landowska','mam','anna dart','pinkhas',
    'serhiy berezin','werner smith','claude sauzet','bollee patino','antoni dragan',
    'herold van den berg','alain bulle','veronika ban','birgit gunther','aisylu burangulova',
    'jacinthe lamontagne-lecomte','sjoddy','adele bessy','patrizia casagranda',
    'giampiero abate','johanna sanna','oliver feistmantl','philippe vignal','fabien delaube',
    'rouzbeh tahmassian','nat stresser','adriana molder','dominique dupin','eric delahaye',
    'ivan grozdanovski','islam-kant','jeanne','pablo salvador rocha','mo tuncay',
    'silvia pavlova','raul alvarez','bus tomasi','eric zener','valerian lenud',
    'carsten westphal','eric munsch','jake','simone butturini','jesus valencia',
    'jauss & gauger','trebbeol mada','martta garcia ramo','philippe euger','sophie cousineau',
    'sarah kube','hubert ollivier','ger bruens','julia blackshaw','francoise schneider',
    'cfey','daria kolosova','bruce peebles','caroline montigneaux','samir farah',
    'steven kern','sabine ducarn','michelle kranz','paolo campa','larissa eremeeva',
    'tarja laine','martin koster','fabrizio sironi','hans everaert','christopher henry',
    'ole muller','jack dufour','glod marcin','quintana martelo','pablo rodriguez guy',
    'jacqueline engels','alauda georges','sam bergwein','massimiliano precisi',
    'stella mierendorff','sophie goudman-peachey','rudi art peters','prof. dr. silke kettig',
    'laetitia vasseur','theo papathomas'
  ]) AS artist_name
  WHERE TRIM(artist_name) != ''
),

query_counts AS (
  SELECT
    LOWER(TRIM(query)) AS query_normalized,
    COUNT(*)           AS nb_searches
  FROM `singulart.sgt_tracking_visitors_algolia_queries`
  WHERE query IS NOT NULL
    AND LENGTH(TRIM(query)) >= 3
  GROUP BY 1
)

SELECT
  al.artist_name,
  SUM(qc.nb_searches) AS total_searches,
  COUNT(DISTINCT qc.query_normalized) AS nb_distinct_queries
FROM artist_list al
JOIN query_counts qc
  ON qc.query_normalized = al.artist_name
  OR STARTS_WITH(qc.query_normalized, CONCAT(al.artist_name, ' '))
  OR (STARTS_WITH(al.artist_name, qc.query_normalized) AND LENGTH(qc.query_normalized) >= 4)
GROUP BY al.artist_name
ORDER BY total_searches DESC
